#!/usr/bin/python
from optparse import OptionParser, make_option
import sys
import dbus

bus = dbus.SystemBus()

if (len(sys.argv) < 1):
        print("Usage: %s <command>" % (sys.argv[0]))
        print("")
        print("  info")
        print("  uuid [Uuid]")
        print("  port [Port]")
        sys.exit(1)

props = dbus.Interface(bus.get_object("br.org.cesar.knot", "/"), "org.freedesktop.DBus.Properties")

cmd = sys.argv[1]
print ("Command: %s" % cmd)

if (cmd == "info"):
	print (props.GetAll("br.org.cesar.knot.Settings1"))
	sys.exit(0)

if (cmd == "uuid"):
	print ("Uuid ...")
	uuid = props.Get("br.org.cesar.knot.Settings1", "Uuid")
	print ("Current Uuid: %s" % uuid)
	value = dbus.String(sys.argv[2])
	props.Set("br.org.cesar.knot.Settings1", "Uuid", value)
	uuid = props.Get("br.org.cesar.knot.Settings1", "Uuid")
	print ("New Uuid: %s" % uuid)

	sys.exit(0)

if (cmd == "host"):
	print ("Host ...")
	host = props.Get("br.org.cesar.knot.Settings1", "Host")
	print ("Current Host: %s" % host)
	value = dbus.String(sys.argv[2])
	props.Set("br.org.cesar.knot.Settings1", "Host", value)
	host = props.Get("br.org.cesar.knot.Settings1", "Host")
	print ("New Host: %s" % host)

	sys.exit(0)

if (cmd == "port"):
	print ("Uuid ...")
	port = props.Get("br.org.cesar.knot.Settings1", "Port")
	print ("Current port: %u" % port)
	value = dbus.UInt16(sys.argv[2])
	props.Set("br.org.cesar.knot.Settings1", "Port", value)
	port = props.Get("br.org.cesar.knot.Settings1", "Port")
	print ("New Uuid: %u" % port)

	sys.exit(0)

if (cmd == "token"):
	print ("Token ...")
	token = props.Get("br.org.cesar.knot.Settings1", "Token")
	print ("Current Token: %s" % token)
	value = dbus.String(sys.argv[2])
	props.Set("br.org.cesar.knot.Settings1", "Token", value)
	token = props.Get("br.org.cesar.knot.Settings1", "Token")
	print ("New Token: %s" % token)

	sys.exit(0)
