#!/usr/bin/python
#
#  This file is part of the KNOT Project
#
#  Copyright (c) 2018, CESAR. All rights reserved.
#
#   This library is free software; you can redistribute it and/or
#   modify it under the terms of the GNU Lesser General Public
#   License as published by the Free Software Foundation; either
#   version 2.1 of the License, or (at your option) any later version.
#
#   This library is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   Lesser General Public License for more details.
#
#   You should have received a copy of the GNU Lesser General Public
#   License along with this library; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

import argparse
import sys
import dbus

bus = dbus.SystemBus()

parser = argparse.ArgumentParser(description='Script to test Dbus settings interface')
parser.add_argument('command', metavar='COMMAND', type=str, nargs='?',
                    choices=['uuid', 'token', 'host', 'port', 'info'],
                    help='Commands: [info, uuid, token, host, port]')
parser.add_argument('value', metavar='VALUE', nargs='?',
										help='value')
options = parser.parse_args()

props = dbus.Interface(bus.get_object("br.org.cesar.knot", "/"), "org.freedesktop.DBus.Properties")

cmd = options.command
cmd_value = options.value

print ("Command: %s" % cmd)

if (cmd == "info"):
	print (props.GetAll("br.org.cesar.knot.Settings1"))
	sys.exit(0)

if not cmd_value:
	raise Exception('Missing value')

if (cmd == "uuid"):
	print ("Uuid ...")
	uuid = props.Get("br.org.cesar.knot.Settings1", "Uuid")
	print ("Current Uuid: %s" % uuid)
	props.Set("br.org.cesar.knot.Settings1", "Uuid", cmd_value)
	uuid = props.Get("br.org.cesar.knot.Settings1", "Uuid")
	print ("New Uuid: %s" % uuid)

	sys.exit(0)

if (cmd == "host"):
	print ("Host ...")
	host = props.Get("br.org.cesar.knot.Settings1", "Host")
	print ("Current Host: %s" % host)
	props.Set("br.org.cesar.knot.Settings1", "Host", cmd_value)
	host = props.Get("br.org.cesar.knot.Settings1", "Host")
	print ("New Host: %s" % host)

	sys.exit(0)

if (cmd == "port"):
	print ("Port ...")
	port = props.Get("br.org.cesar.knot.Settings1", "Port")
	print ("Current port: %u" % port)
	props.Set("br.org.cesar.knot.Settings1", "Port", dbus.UInt16(cmd_value))
	port = props.Get("br.org.cesar.knot.Settings1", "Port")
	print ("New Port: %u" % port)

	sys.exit(0)

if (cmd == "token"):
	print ("Token ...")
	token = props.Get("br.org.cesar.knot.Settings1", "Token")
	print ("Current Token: %s" % token)
	props.Set("br.org.cesar.knot.Settings1", "Token", cmd_value)
	token = props.Get("br.org.cesar.knot.Settings1", "Token")
	print ("New Token: %s" % token)

	sys.exit(0)
